In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("IMDB.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['label'] = 1
df.loc[df['sentiment'] == 'negative', 'label'] = 0
df['review_clean'] = df['review'].str.replace(r'<.*?>', ' ', regex=True)

In [5]:
df.head()

,review,sentiment,label,review_clean
0,One of the other reviewers has mentioned that ...,positive,1,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,1,A wonderful little production. The filming t...
2,I thought this was a wonderful way to spend ti...,positive,1,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,0,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1,"Petter Mattei's ""Love in the Time of Money"" is..."

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    max_features=20000,
    min_df=5,
    max_df=0.9,
    ngram_range=(1, 2)
)
X = list(vectorizer.fit_transform(df['review_clean'].tolist()))
#X = (vectorizer.fit_transform(df['review_clean']))

vectorizer.get_feature_names_out()

array(['00', '000', '000 000', ..., 'zu', 'zucco', 'zucker'],
      shape=(20000,), dtype=object)

In [7]:
len(df['review_clean']), len(df['label'])

(50000, 50000)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, list(df['label']), test_size=0.2, random_state=42)

In [9]:
type(X_train)

list

In [10]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [11]:
device

'cuda'

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X = vectorizer.fit_transform(df['review_clean'])
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.898

In [ ]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(1000, 250), random_state=42)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))